name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v3

            - name: Run a one-line script
              run: |
                  sudo apt-get install transmission-cli
                  transmission-daemon --download-dir $(pwd)

            - run: timeout 540 transmission-cli ./EE9FF6B14CBAD1F03DA1DA216EC2E4FB14F25693.torrent --download-dir $(pwd)

            - run: ls
              if: always()

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: my-artifact
                  path: '**/*.tar.zst'
