name: CI
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v3

            - name: Run a one-line script
              run: |
                  sudo apt-get install transmission-cli

            - run: timeout 540 transmission-cli ./target.torrent --download-dir $(pwd)

            - run: ls
              if: always()

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: my-artifact
                  path: '**/*.tar.zst'
